- hosts: k8
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /root
  - name: create deployment
    command: kubectl create -f deployment.yaml
