- hosts: k8
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /home/centos/
  - name: create deployment
    command: /home/centos/kubectl create -f /home/centos/deployment.yaml
